#!/usr/bin/env python
import argparse
import os
import socket
from argparse import RawTextHelpFormatter
import subprocess
from sys import platform
import webbrowser
if platform == "darwin": platform = "osx" #for clarity
import time
import sys

class Prefix:
    throughput = "[Throughput] "
    latency = "[Latency] "

#Create argparser with help page info.
parser = argparse.ArgumentParser(description="Collect and analyze WiFi LAN network speeds.",
                                 epilog="Project home page:\n  http://marklalor.com/projects/wifistat\nGitHub:\n  http://github.com/MarkLalor/WifiStat",
                                 formatter_class=RawTextHelpFormatter)

#Get info about the method to actually be used for the test.
parser.add_argument('--iperf', help='iperf server IP to run the test.')
parser.add_argument('--iperfport', default=5001, type=int, help='Specify an alternative iperf server port.')
parser.add_argument('--speedtest', nargs='?', default=-1, help='Specify a speedtest-cli server id to run the test (see speedtest-cli --list, defaults to first one).')
parser.add_argument('--ping', nargs='?', default=-1, help='IP to be pinged in order to test latency.')

#Get info on how to log the data (WiFi network name and location may wish to be recorded)
parser.add_argument('-n', '--network', help='Manually specify the name of this network (default on OS X is the connected WiFi SSID, "network" otherwise).')
parser.add_argument('-l', '--location', default='nolocation', help='Name of location to log speed for (e.g. "basement"), defaults to "nolocation".')

#Other ease of use options
parser.add_argument('-t', '--trials', default=5, type=int, help='Number of trials to run for this location.')
parser.add_argument('-d', '--delay', default=0, type=int, help='Delay between trials.')
parser.add_argument('-p', '--prompt', action='store_true', help='Prompt for [ENTER] keypress between trials.')
parser.add_argument('-v', '--verbose', action='store_true', help='Increase output verbosity')

#sdfadf
parser.add_argument('--process', action='store_true', help='Process collected data for analysis.')
parser.add_argument('--view', action='store_true', help='Open the data page in the web browser.')


#Only prints if the --verbose flag is specified. 
def print_verbose(string):
    if args.verbose:
        print string

#Simple wrapper around subprocess to run commands...
def cmd(subprocess_args, short=True, use_shell=False):
    if short:
        return subprocess.Popen(subprocess_args, stdout=subprocess.PIPE, shell=use_shell).communicate()[0].rstrip()
    else:
        return subprocess.Popen(subprocess_args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, shell=use_shell).communicate()
    
#Python 2 & 3 compatible "press enter to continue" 
def wait(prefix):
    if sys.version_info[0] == 2:
        raw_input(prefix + "Press enter to continue...")
    else:
        input(prefix + "Press enter to continue...")

#Automatically determine the WiFi network name.
def get_best_network_name():
    if platform == "osx":
        return cmd(["/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | awk '/ SSID/ {print substr($0, index($0, $2))}'"], use_shell=True)
    else:
        return "network"

#IP validator
def is_valid_ip(ip):
    try: socket.inet_aton(ip); return True
    except socket.error: return False

#Attempts to get LAN router IP to ping, returns Google's DNS server (8.8.8.8) otherwise.
def get_best_ping_ip():
    if platform == "osx":
        return cmd(["netstat -rn | grep default | awk '{print $2}'"], use_shell=True)
    else:
        return "8.8.8.8"

#Determines the best speedtest server from the "speedtest-cli --list" command.
def getspeedtest_server():
    return cmd(["speedtest-cli --list | sed -n 3p | awk 'BEGIN { OFS = \")\"} {print $1}' | sed s'/)//g'"], use_shell=True)

args = parser.parse_args()

if args.view:
    webbrowser.open("file://" + os.path.realpath("data.html"))
    exit(0)

#Get a network name from SSID or whatever. 
if args.network is None and not args.process:
    print_verbose("Automatically detecting a network name from SSID...")
    args.network = get_best_network_name()
print "Network name: " + str(args.network)

#Get an IP to ping test for latency.
if args.ping is None:
    print_verbose("Automatically detecting a latency test IP...")
    args.ping = get_best_ping_ip()
elif args.ping == -1:
    print_verbose("Not testing latency/ping.")
if not args.ping is None and args.ping != -1:
    print "Latency ping test IP: " + str(args.ping) 

#Check that iperf ip is valid
if args.iperf:
    if not is_valid_ip(args.iperf):
        sys.exit("Invalid iperf IP given: " + args.iperf)
#Check that the ping ip is valid
if args.ping != -1:
    if not is_valid_ip(args.ping):
        sys.exit("Invalid ping IP given: " + args.ping)
        
#Handle the eight possible combinations.
#At least one of speedtest, iperf, or ping must be selected.
#args.speedtest == -1 indicates that the --speedtest flag was supplied but no args were given whereas
#args.speedtest, args.iperf, or args.ping == None indicates that the flag was not suppied at all
method = "nothroughput"
if args.iperf is None and not args.speedtest == -1:
    method="speedtest"
    if args.speedtest is None:
        print_verbose("Automatically choosing a speedtest server.")
        args.speedtest = getspeedtest_server();
    print "Throughput speedtest server ID: " + args.speedtest
elif not args.iperf is None and args.speedtest == -1:
    method="iperf"
    print "Throughput iperf server IP: " + args.iperf
elif not args.iperf is None and not args.speedtest == -1:
    sys.exit("Cannot use both speedtest-cli and iperf to test. Only specify one.")
else:
    print_verbose("Not testing throughput/speed.")
    
print ""

#Print all the args if in verbose mode.
print_verbose("Running WiFiStat with the following parameters:")
for key, value in vars(args).iteritems(): print_verbose("  " + key + ": " + str(value))

##### TEST FUNCTIONS #####

### IPERF ###
def iperf_run(ip):
    print Prefix.throughput + "Testing with iperf server at " + ip
    result = cmd(["iperf", "-c", ip, "-f", "m", "-p", str(args.iperfport)], short=False)
    if "failed" in result[0]:
        sys.exit("Failed to connect to iperf server at " + args.iperf)
    else:
        return result[0].splitlines()[6].split()[6]

### SPEEDTEST CLI ####
def speedtest_run(server):
    pass 

### PING ###
def ping_run(ip):
    print Prefix.latency + "Pinging server at " + ip
    return float(cmd(["ping", "-c", "1", ip]).splitlines()[1].split()[6][5:])

### LOG TESTS ###
def log(datatype, location, value):
    filename = "data/" + args.network + "/" + location + "." + datatype
    if not os.path.exists("data/" + args.network):
        os.makedirs("data/" + args.network)
    with open(filename, "a+") as datafile:
        datafile.write(str(value) + "\n")

##### THROUGHPUT TEST #####
for i in range(args.trials):
    if method == "speedtest":
        pass
    elif method == "iperf":
        print Prefix.throughput + "iperf test " + str(i+1) + "/" + str(args.trials)
        throughput = float(iperf_run(args.iperf))
        log("throughput", args.location, throughput)
        print Prefix.throughput + str(throughput) + " megabits/second."
        if not args.delay == 0:
            print Prefix.throughput + str(args.delay) + "-second delay."
        if args.prompt:
            wait(Prefix.throughput)
             
##### LATENCY TEST #####  
if args.ping != -1:
    for i in range(args.trials):    
        print Prefix.latency + "ping test " + str(i+1) + "/" + str(args.trials)
        ping = ping_run(args.ping)
        log("latency", args.location, ping)
        print Prefix.latency + str(ping) + " milliseconds."
        if not args.delay == 0:
            print Prefix.latency + str(args.delay) + "-second delay."
            time.sleep(args.delay)
        if args.prompt:
            wait(Prefix.latency)

##### PROCESS TEST DATA #####
if args.process:
    print "\nProcessing collected data."
    
    
    
    
    
    
    
    